CREATE TABLE `tl_theme_default_home_page_sections` (
  `id` int(11) NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT 0,
  `status` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `tl_theme_default_home_page_sections_properties`
--

CREATE TABLE `tl_theme_default_home_page_sections_properties` (
  `id` int(11) NOT NULL,
  `section_id` int(11) DEFAULT NULL,
  `key_name` text DEFAULT NULL,
  `key_value` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `tl_theme_option_settings`
--

CREATE TABLE `tl_theme_option_settings` (
  `id` bigint(20) NOT NULL,
  `theme_id` int(11) DEFAULT NULL,
  `option_name` text DEFAULT NULL,
  `field_name` text DEFAULT NULL,
  `field_value` longtext DEFAULT NULL,
  `field_reset_value` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tl_theme_option_settings`
--

INSERT INTO `tl_theme_option_settings` (`id`, `theme_id`, `option_name`, `field_name`, `field_value`, `field_reset_value`) VALUES
(4155, 15, 'header', 'custom_header', NULL, NULL),
(4156, 15, 'header', 'header_bg_color', '#4b32a5', NULL),
(4157, 15, 'header', 'header_bg_color_transparent', '0', NULL),
(4158, 15, 'header', 'sticky_header_bg_color', '', NULL),
(4159, 15, 'header', 'sticky_header_bg_color_transparent', '0', NULL),
(4160, 15, 'header', 'header_reg_bg_color', '', NULL),
(4161, 15, 'header', 'header_reg_bg_color_transparent', '0', NULL),
(4162, 15, 'header', 'header_reg_color', '#ffffff', NULL),
(4163, 15, 'header', 'header_reg_color_transparent', '0', NULL),
(4164, 15, 'header', 'sticky_header_reg_bg_color', '', NULL),
(4165, 15, 'header', 'sticky_header_reg_bg_color_transparent', '0', NULL),
(4166, 15, 'header', 'sticky_header_reg_color', '#ffffff', NULL),
(4167, 15, 'header', 'sticky_header_reg_color_transparent', '0', NULL),
(4168, 15, 'header_logo', 'custom_header_logo', NULL, NULL),
(4169, 15, 'header_logo', 'logo_dimension_width', NULL, NULL),
(4170, 15, 'header_logo', 'logo_dimension_height', NULL, NULL),
(4171, 15, 'header_logo', 'logo_dimension_unit', NULL, NULL),
(4172, 15, 'header_logo', 'logo_margin_top', NULL, NULL),
(4173, 15, 'header_logo', 'logo_margin_bottom', NULL, NULL),
(4174, 15, 'header_logo', 'logo_margin_unit', NULL, NULL),
(4175, 15, 'header_logo', 'sticky_logo_dimension_width', NULL, NULL),
(4176, 15, 'header_logo', 'sticky_logo_dimension_height', NULL, NULL),
(4177, 15, 'header_logo', 'sticky_logo_dimension_unit', NULL, NULL),
(4178, 15, 'header_logo', 'sticky_logo_margin_top', NULL, NULL),
(4179, 15, 'header_logo', 'sticky_logo_margin_bottom', NULL, NULL),
(4180, 15, 'header_logo', 'sticky_logo_margin_unit', NULL, NULL),
(4181, 15, 'menu', 'custom_menu', NULL, NULL),
(4182, 15, 'menu', 'menu_color', '', NULL),
(4183, 15, 'menu', 'menu_color_transparent', '0', NULL),
(4184, 15, 'menu', 'menu_hover_color', '#4ad98f', NULL),
(4185, 15, 'menu', 'menu_hover_color_transparent', '0', NULL),
(4186, 15, 'menu', 'menu_active_color', NULL, NULL),
(4187, 15, 'menu', 'menu_active_color_transparent', NULL, NULL),
(4188, 15, 'subscribe', 'mailchimp_api_key', '', NULL),
(4189, 15, 'subscribe', 'mailchimp_list_id', '', NULL),
(4190, 15, 'subscribe', 'custom_subscription', NULL, NULL),
(4191, 15, 'subscribe', 'subscribe_form_button_text', 'Subscribe', NULL),
(4192, 15, 'subscribe', 'form_input_color', NULL, NULL),
(4193, 15, 'subscribe', 'form_input_color_transparent', NULL, NULL),
(4194, 15, 'subscribe', 'form_input_text_color', NULL, NULL),
(4195, 15, 'subscribe', 'form_input_text_color_transparent', NULL, NULL),
(4196, 15, 'subscribe', 'form_submit_button_color', NULL, NULL),
(4197, 15, 'subscribe', 'form_submit_button_color_transparent', NULL, NULL),
(4198, 15, 'subscribe', 'form_submit_button_bg_color', NULL, NULL),
(4199, 15, 'subscribe', 'form_submit_button_bg_color_transparent', NULL, NULL),
(4200, 15, 'subscribe', 'form_submit_button_hover_color', NULL, NULL),
(4201, 15, 'subscribe', 'form_submit_button_hover_color_transparent', NULL, NULL),
(4202, 15, 'subscribe', 'form_submit_button_bg_hover_color', NULL, NULL),
(4203, 15, 'subscribe', 'form_submit_button_bg_hover_color_transparent', NULL, NULL),
(4204, 15, 'social', 'social_field', '[{\"social_icon_title\":\"Facebook\",\"social_icon\":\"fa-facebook\",\"social_icon_url\":\"#\",\"order\":1},{\"social_icon_title\":\"Instagram\",\"social_icon\":\"fa-instagram\",\"social_icon_url\":\"#\",\"order\":2},{\"social_icon_title\":\"Twitter\",\"social_icon\":\"fa-twitter\",\"social_icon_url\":\"#\",\"order\":3}]', NULL),
(4205, 15, 'social', 'custom_social', NULL, NULL),
(4206, 15, 'social', 'social_background_color', NULL, NULL),
(4207, 15, 'social', 'social_background_color_transparent', NULL, NULL),
(4208, 15, 'social', 'social_border_color', NULL, NULL),
(4209, 15, 'social', 'social_border_color_transparent', NULL, NULL),
(4210, 15, 'social', 'social_color', NULL, NULL),
(4211, 15, 'social', 'social_color_transparent', NULL, NULL),
(4212, 15, 'social', 'social_hover_color', NULL, NULL),
(4213, 15, 'social', 'social_hover_color_transparent', NULL, NULL),
(4214, 15, 'social', 'social_hover_border_color', NULL, NULL),
(4215, 15, 'social', 'social_hover_border_color_transparent', NULL, NULL),
(4216, 15, 'social', 'social_hover_background_color', NULL, NULL),
(4217, 15, 'social', 'social_hover_background_color_transparent', NULL, NULL),
(4218, 15, 'subscribe', 'subscription_section_title', NULL, NULL),
(4219, 15, 'subscribe', 'subscription_section_short_text', NULL, NULL),
(4222, 15, 'header', 'regisstratiion_button_text', NULL, NULL),
(4233, 15, 'preloader', 'preloader_field', '1', NULL),
(4234, 15, 'preloader', 'preloader_style_type', 'default', NULL),
(4235, 15, 'preloader', 'preloader_item_color', '', NULL),
(4236, 15, 'preloader', 'preloader_item_color_transparent', '0', NULL),
(4237, 15, 'preloader', 'preloader_bgcolor', '', NULL),
(4238, 15, 'preloader', 'preloader_bgcolor_transparent', '0', NULL),
(4240, 15, 'header', 'registratiion_button_text', 'Sign Up', NULL),
(4241, 15, 'header', 'login_button_text', 'Login', NULL),
(4242, 15, 'header', 'header_login_bg_color', '', NULL),
(4243, 15, 'header', 'header_login_bg_color_transparent', '0', NULL),
(4244, 15, 'header', 'header_login_color', '#ffffff', NULL),
(4245, 15, 'header', 'header_login_color_transparent', '0', NULL),
(4246, 15, 'header', 'sticky_header_login_bg_color', '', NULL),
(4247, 15, 'header', 'sticky_header_login_bg_color_transparent', '0', NULL),
(4248, 15, 'header', 'sticky_header_login_color', '#ffffff', NULL),
(4249, 15, 'header', 'sticky_header_login_color_transparent', '0', NULL),
(4250, 15, 'auth_layout', 'user_reg_bg_image', '1058', NULL),
(4251, 15, 'auth_layout', 'user_login_bg_image', '1058', NULL),
(4252, 15, 'back_to_top', 'back_to_top_button', '1', NULL),
(4253, 15, 'back_to_top', 'custom_back_to_top_button', '1', NULL),
(4254, 15, 'back_to_top', 'custom_back_to_top_button_icon', '', NULL),
(4255, 15, 'back_to_top', 'back_to_top_button_bgcolor', '#5dd9c1', NULL),
(4256, 15, 'back_to_top', 'back_to_top_button_bgcolor_transparent', '0', NULL),
(4257, 15, 'back_to_top', 'back_to_top_button_color', '', NULL),
(4258, 15, 'back_to_top', 'back_to_top_button_color_transparent', '0', NULL),
(4259, 15, 'back_to_top', 'back_to_top_button_hover_color', '', NULL),
(4260, 15, 'back_to_top', 'back_to_top_button_hover_color_transparent', '0', NULL),
(4261, 15, 'back_to_top', 'back_to_top_button_hover_bgcolor', '', NULL),
(4262, 15, 'back_to_top', 'back_to_top_button_hover_bgcolor_transparent', '0', NULL),
(4263, 15, 'preloader', 'custom_preloader_type', NULL, NULL),
(4264, 15, 'preloader', 'preloader_image', NULL, NULL),
(4265, 15, 'preloader', 'preloader_html', NULL, NULL),
(4266, 15, 'preloader', 'preloader_heading_tag', NULL, NULL),
(4267, 15, 'preloader', 'preloader_text', NULL, NULL),
(4268, 15, 'subscribe', 'enable_subscription', NULL, NULL),
(4269, 15, 'header', 'language_option', '1', NULL),
(4270, 15, 'home_page', 'homepage_layout', 'full_layout', NULL),
(4271, 15, 'theme_color', 'theme_primary_color', '#4e2ea9', NULL),
(4272, 15, 'header', 'header_search_icon', '0', NULL),
(4273, 15, 'header', 'header_search_icon_color', NULL, NULL),
(4274, 15, 'header', 'header_search_icon_color_transparent', NULL, NULL),
(4275, 15, 'header', 'sticky_header_search_icon_color', NULL, NULL),
(4276, 15, 'header', 'sticky_header_search_icon_color_transparent', NULL, NULL),
(4280, 15, 'footer', 'footer_content', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.', NULL),
(4281, 15, 'footer', 'custom_footer_style', '1', NULL),
(4282, 15, 'footer', 'footer_language_select', '1', NULL),
(4289, 15, 'subscribe', 'footer_subscribe_form', '1', NULL),
(4290, 15, 'subscribe', 'subscribe_form_title', 'Subscribe Newsletter', NULL),
(4291, 15, 'subscribe', 'subscribe_form_placeholder', 'Enter Your Email', NULL),
(4292, 15, 'subscribe', 'privacy_policy', '1', NULL),
(4293, 15, 'subscribe', 'privacy_policy_page', '14', NULL),
(4294, 15, 'subscribe', 'custom_footer_subscribe', '0', NULL),
(4295, 15, 'subscribe', 'form_privacy_text_color', NULL, NULL),
(4296, 15, 'subscribe', 'form_privacy_text_color_transparent', NULL, NULL),
(4297, 15, 'subscribe', 'form_privacy_text_anchor_color', NULL, NULL),
(4298, 15, 'subscribe', 'form_privacy_text_anchor_color_transparent', NULL, NULL),
(4299, 15, 'subscribe', 'form_bg_color', NULL, NULL),
(4300, 15, 'subscribe', 'form_bg_color_transparent', NULL, NULL),
(4301, 15, 'subscribe', 'form_title_color', NULL, NULL),
(4302, 15, 'subscribe', 'form_title_color_transparent', NULL, NULL),
(4303, 15, 'page', 'custom_page_c', '1', NULL),
(4304, 15, 'page', 'page_title_c', '1', NULL),
(4305, 15, 'page', 'page_background-color', '#4e2ea9', NULL),
(4306, 15, 'page', 'page_background-color-transparent_i', '0', NULL),
(4307, 15, 'page', 'page_background-repeat', '', NULL),
(4308, 15, 'page', 'page_background-size', '', NULL),
(4309, 15, 'page', 'page_background-attachment', '', NULL),
(4310, 15, 'page', 'page_background-position', '', NULL),
(4311, 15, 'page', 'page_background-image', '', NULL),
(4312, 15, 'page', 'page_background_image_i', '', NULL),
(4313, 15, 'page', 'overlay_c', '0', NULL),
(4314, 15, 'page', 'breadcrumb_hide_show_c', '1', NULL),
(4315, 15, 'page', 'page_title_tag_s', 'h1', NULL),
(4316, 15, 'page', 'page_title_typography_google_link_s', '', NULL),
(4317, 15, 'page', 'page_title_typography_css_i', '{\"color\":\"#fcfcfc\"}', NULL),
(4318, 15, 'page', 'page_title_font_unit_i', 'px', NULL),
(4319, 15, 'page', 'page_title_font_font-family', '', NULL),
(4320, 15, 'page', 'page_title_font_font-style', '', NULL),
(4321, 15, 'page', 'page_title_font_font-weight', '', NULL),
(4322, 15, 'page', 'page_title_font_weight_style_i', '', NULL),
(4323, 15, 'page', 'page_title_font_font-subsets_i', '', NULL),
(4324, 15, 'page', 'page_title_font_u_font-size', '', NULL),
(4325, 15, 'page', 'page_title_font_u_line-height', '', NULL),
(4326, 15, 'page', 'page_title_font_u_word-spacing', '', NULL),
(4327, 15, 'page', 'page_title_font_u_letter-spacing', '', NULL),
(4328, 15, 'page', 'page_title_font_color', '#ffffff', NULL),
(4329, 15, 'blog', 'custom_blog_style', '1', NULL),
(4330, 15, 'blog', 'blog_post_style', 's_one', NULL),
(4331, 15, 'blog', 'blog_page_title', '1', NULL),
(4332, 15, 'blog', 'blog_posts_excerpt', '0', NULL),
(4333, 15, 'blog', 'blog_perpage', '6', NULL),
(4334, 15, 'blog', 'read_more_text_setting', 'default', NULL),
(4335, 15, 'blog', 'blog_pagination_setting', 'number', NULL),
(4336, 15, 'blog', 'blog_pagination_color', '#ffffff', NULL),
(4337, 15, 'blog', 'blog_pagination_color_transparent', '0', NULL),
(4338, 15, 'blog', 'blog_pagination_bg_color', '#4e2ea9', NULL),
(4339, 15, 'blog', 'blog_pagination_bg_color_transparent', '0', NULL),
(4340, 15, 'blog', 'blog_pagination_hover_color', '', NULL),
(4341, 15, 'blog', 'blog_pagination_hover_color_transparent', '0', NULL),
(4342, 15, 'blog', 'footer_back_ground_image', '1059', NULL),
(4343, 15, 'blog', 'blog_breadcrumb_section_bg_color', '#ff0000', NULL),
(4344, 15, 'blog', 'blog_breadcrumb_section_bg_color_transparent', '0', NULL),
(4345, 15, 'blog', 'blog_breadcrumb_section_color', '#24a800', NULL),
(4346, 15, 'blog', 'blog_breadcrumb_section_color_transparent', '0', NULL),
(4347, 15, 'blog', 'blog_breadcrumb_section_active_color', '#1700c7', NULL),
(4348, 15, 'blog', 'blog_breadcrumb_section_active_color_transparent', '0', NULL),
(4349, 15, 'blog', 'blog_breadcrumb_section_hover_color', '#bfc200', NULL),
(4350, 15, 'blog', 'blog_breadcrumb_section_hover_color_transparent', '0', NULL),
(4351, 15, 'blog', 'blog_breadcrumb_section_bg_image', '1059', NULL),
(4352, 15, 'blog', 'blog_page_title_setting', 'default', NULL),
(4353, 15, 'header', 'dash_button_text', 'Dashboard', NULL),
(4354, 15, 'header', 'header_dash_bg_color', '', NULL),
(4355, 15, 'header', 'header_dash_bg_color_transparent', '0', NULL),
(4356, 15, 'header', 'header_dash_color', '#ffffff', NULL),
(4357, 15, 'header', 'header_dash_color_transparent', '0', NULL),
(4358, 15, 'header', 'sticky_header_dash_bg_color', '', NULL),
(4359, 15, 'header', 'sticky_header_dash_bg_color_transparent', '0', NULL),
(4360, 15, 'header', 'sticky_header_dash_color', '#ffffff', NULL),
(4361, 15, 'header', 'sticky_header_dash_color_transparent', '0', NULL),
(4362, 15, 'blog', 'blog_pagination_hover_bg_color', '', NULL),
(4363, 15, 'blog', 'blog_pagination_hover_bg_color_transparent', '0', NULL),
(4364, 15, 'page', 'breadcrumb_color', '#ffffff', NULL),
(4365, 15, 'page', 'breadcrumb_color-transparent_i', '0', NULL),
(4366, 15, 'page', 'breadcrumb_activer_color', '#e68f8f', NULL),
(4367, 15, 'page', 'breadcrumb_activer_color-transparent_i', '0', NULL),
(4368, 15, 'page', 'breadcrumb_divider_background-color', '#ffffff', NULL),
(4369, 15, 'page', 'breadcrumb_divider_background-color-transparent_i', '0', NULL),
(4370, 15, 'back_to_top', 'back_to_top_button_on_mobile', '0', NULL),
(4371, 15, 'footer', 'footer_bg_color', '#4b32a5', NULL),
(4372, 15, 'footer', 'footer_bg_color_transparent', '0', NULL),
(4373, 15, 'footer', 'custom_footer_padding_top', '80', NULL),
(4374, 15, 'footer', 'custom_footer_padding_bottom', '', NULL),
(4375, 15, 'footer', 'custom_footer_padding_unit', 'px', NULL),
(4376, 15, 'footer', 'footer_social_enable', '1', NULL),
(4377, 15, 'footer', 'footer_logo_enable', '1', NULL),
(4378, 15, 'footer', 'footer_text_enable', '1', NULL),
(4379, 15, 'footer', 'footer_social_color', '', NULL),
(4380, 15, 'footer', 'footer_social_color_transparent', '0', NULL),
(4381, 15, 'footer', 'footer_social_hover_color', '', NULL),
(4382, 15, 'footer', 'footer_social_hover_color_transparent', '0', NULL),
(4383, 15, 'footer', 'footer_text_color', '', NULL),
(4384, 15, 'footer', 'footer_text_color_transparent', '0', NULL),
(4385, 15, 'footer', 'footer_anchor_text_color', '', NULL),
(4386, 15, 'footer', 'footer_anchor_text_color_transparent', '0', NULL),
(4387, 15, 'footer', 'footer_anchor_text_hover_color', '', NULL),
(4388, 15, 'footer', 'footer_anchor_text_hover_color_transparent', '0', NULL),
(4389, 15, 'footer', 'footer_color', '', NULL),
(4390, 15, 'footer', 'footer_color_transparent', '0', NULL),
(4391, 15, 'footer', 'footer_link_color', '', NULL),
(4392, 15, 'footer', 'footer_link_color_transparent', '0', NULL),
(4393, 15, 'footer', 'footer_link_hover_color', '', NULL),
(4394, 15, 'footer', 'footer_link_hover_color_transparent', '0', NULL),
(4395, 15, 'footer', 'copyright_bg_color', '#6653ac', NULL),
(4396, 15, 'footer', 'copyright_bg_color_transparent', '0', NULL),
(4397, 15, 'header', 'header_text_color', '', NULL),
(4398, 15, 'header', 'header_text_color_transparent', '0', NULL),
(4399, 15, 'header', 'header_sticky_text_color', '', NULL),
(4400, 15, 'header', 'header_sticky_text_color_transparent', '0', NULL),
(4401, 15, 'menu', 'custom_menu_style', '1', NULL),
(4402, 15, 'mobile_menu', 'custom_mobile_menu_style', '0', NULL),
(4403, 15, 'footer', 'footer_logo_anchor_url', '', NULL),
(4404, 15, 'blog', 'blog_layout', 'right_sidebar_layout', NULL),
(4405, 15, 'blog', 'blog_colum', 'blog_colum_1', NULL),
(4406, 15, 'blog', 'blog_pagination_active_color', '', NULL),
(4407, 15, 'blog', 'blog_pagination_active_color_transparent', '0', NULL),
(4408, 15, 'blog', 'blog_pagination_active_bg_color', '#56b88e', NULL),
(4409, 15, 'blog', 'blog_pagination_active_bg_color_transparent', '0', NULL),
(4410, 15, 'menu', 'menu_active_item_color', '', NULL),
(4411, 15, 'menu', 'menu_active_item_color_transparent', '0', NULL),
(4412, 15, 'menu', 'sub_menu_color', '', NULL),
(4413, 15, 'menu', 'sub_menu_color_transparent', '0', NULL),
(4414, 15, 'menu', 'sub_menu_hover_color', '', NULL),
(4415, 15, 'menu', 'sub_menu_hover_color_transparent', '0', NULL),
(4416, 15, 'menu', 'sub_menu_active_item_color', '', NULL),
(4417, 15, 'menu', 'sub_menu_active_item_color_transparent', '0', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `tl_theme_sidebars`
--

